#ifndef EXTCONF_H
#define EXTCONF_H
#define HAVE_TYPE_INT_LEAST8_T 1
#define HAVE_TYPE_INT_LEAST16_T 1
#define HAVE_TYPE_INT_LEAST32_T 1
#define HAVE_TYPE_INT_LEAST64_T 1
#define HAVE_TYPE_INT_FAST8_T 1
#define HAVE_TYPE_INT_FAST16_T 1
#define HAVE_TYPE_INT_FAST32_T 1
#define HAVE_TYPE_INT_FAST64_T 1
#define HAVE_TYPE_INTMAX_T 1
#define HAVE_TYPE_SIG_ATOMIC_T 1
#define HAVE_TYPE_WCHAR_T 1
#define HAVE_TYPE_WINT_T 1
#define HAVE_TYPE_WCTRANS_T 1
#define HAVE_TYPE_WCTYPE_T 1
#define HAVE_TYPE__BOOL 1
#define HAVE_TYPE_LONG_DOUBLE 1
#define HAVE_TYPE_FLOAT__COMPLEX 1
#define HAVE_TYPE_DOUBLE__COMPLEX 1
#define HAVE_TYPE_LONG_DOUBLE__COMPLEX 1
#define HAVE_TYPE___INT128 1
#define HAVE_TYPE___FLOAT128 1
#define HAVE_TYPE__DECIMAL32 1
#define HAVE_TYPE__DECIMAL64 1
#define HAVE_TYPE__DECIMAL128 1
#define HAVE_TYPE___FLOAT80 1
#endif
