#ifndef EXTCONF_H
#define EXTCONF_H
#define HAVE_TERMIOS_H 1
#define HAVE_CFMAKERAW 1
#define HAVE_SYS_IOCTL_H 1
#define HAVE_RB_SCHEDULER_TIMEOUT 1
#define HAVE_RB_IO_WAIT 1
#define ENABLE_IO_GETPASS 1
#endif
